sources:
  npm: true
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
reviewed:
  npm:
    - bl
    - color-convert
    - fs.realpath
    - glob
    - ieee754
    - json-parse-even-better-errors
    - lodash.camelcase
    - readable-stream
    - string_decoder
    - unbzip2-stream
